@extends('layouts.app')

@section('title', 'Nestor KPADJA — Ingénieur Backend & Architectures Blockchain')

@section('content')
<div class="terminal-grid">
    <section class="relative overflow-hidden"><div class="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(59,130,246,.16),transparent_35%)]"></div><div class="relative mx-auto grid min-h-[calc(100vh-4rem)] max-w-7xl items-center gap-12 px-5 py-16 sm:px-8 lg:grid-cols-12 lg:px-12 lg:py-20">
        <div class="lg:col-span-7"><div class="mb-6 inline-flex items-center gap-2 rounded-full border border-[#1f2c47] bg-[#131c31]/80 px-3 py-1.5 font-mono text-[11px] text-[#94a3b8]"><span class="text-[#3b82f6]">&gt;_</span> SYSTEM_READY :: DISPONIBLE POUR COLLABORER</div><h1 class="max-w-3xl font-display text-4xl font-bold leading-tight tracking-[-.04em] text-white sm:text-5xl lg:text-6xl">Je construis des systèmes <span class="text-[#3b82f6]">fiables</span>, scalables et pensés pour durer.</h1><p class="mt-6 max-w-2xl text-lg leading-8 text-slate-400">Ingénieur backend spécialisé dans les architectures distribuées, les APIs robustes et les protocoles blockchain. Je transforme des problèmes complexes en systèmes clairs et opérables.</p><div class="mt-8 flex flex-wrap gap-3"><a href="#projets" class="rounded-lg bg-[#3b82f6] px-5 py-3 text-sm font-semibold text-white shadow-[0_0_24px_rgba(59,130,246,.25)] transition hover:bg-blue-500">Voir mes projets <span aria-hidden="true">→</span></a><a href="#contact" class="rounded-lg border border-[#1f2c47] px-5 py-3 text-sm font-semibold text-slate-200 transition hover:border-[#3b82f6] hover:bg-[#131c31]">Télécharger mon CV</a></div><div class="mt-12 grid max-w-xl grid-cols-2 gap-4 sm:grid-cols-4"><div><div class="font-display text-2xl font-bold">5+</div><div class="code-label mt-1 text-slate-500">Années exp.</div></div><div><div class="font-display text-2xl font-bold">18</div><div class="code-label mt-1 text-slate-500">Technologies</div></div><div><div class="font-display text-2xl font-bold">24/7</div><div class="code-label mt-1 text-slate-500">Fiabilité</div></div><div><div class="font-display text-2xl font-bold text-emerald-400">100%</div><div class="code-label mt-1 text-slate-500">Engagement</div></div></div></div>
        <div class="lg:col-span-5"><div class="specular-card overflow-hidden p-5 shadow-2xl shadow-blue-950/20"><div class="mb-5 flex items-center justify-between border-b border-[#1f2c47] pb-4 font-mono text-xs text-slate-500"><span><i class="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-red-400"></i><i class="mx-1 inline-block h-2.5 w-2.5 rounded-full bg-amber-400"></i><i class="ml-1 inline-block h-2.5 w-2.5 rounded-full bg-emerald-400"></i></span><span>~/portfolio/profile.json</span></div><pre class="overflow-x-auto font-mono text-sm leading-7 text-slate-300"><span class="text-slate-500">{</span>
  <span class="text-[#3b82f6]">"identity"</span>: <span class="text-slate-500">{</span>
    <span class="text-[#3b82f6]">"name"</span>: <span class="text-amber-300">"Nestor KPADJA"</span>,
    <span class="text-[#3b82f6]">"role"</span>: <span class="text-amber-300">"Backend Engineer"</span>,
    <span class="text-[#3b82f6]">"focus"</span>: [<span class="text-amber-300">"Distributed Systems"</span>, <span class="text-amber-300">"Blockchain"</span>]
  <span class="text-slate-500">}</span>,
  <span class="text-[#3b82f6]">"status"</span>: <span class="text-emerald-400">"available"</span>,
  <span class="text-[#3b82f6]">"location"</span>: <span class="text-amber-300">"Lomé, TG"</span>
<span class="text-slate-500">}</span></pre><div class="mt-5 flex items-center justify-between border-t border-[#1f2c47] pt-4 font-mono text-[11px] text-slate-500"><span>last_deploy: stable</span><span class="text-emerald-400">● operational</span></div></div></div>
    </div></section>

    <section id="apropos" class="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><div class="grid gap-8 lg:grid-cols-3"><div><span class="code-label text-[#3b82f6]">01 // approche</span><h2 class="mt-3 font-display text-3xl font-bold">La rigueur au service du produit.</h2></div><div class="grid gap-4 sm:grid-cols-2 lg:col-span-2"><article class="specular-card p-6"><div class="mb-4 text-2xl text-[#3b82f6]">⌘</div><h3 class="font-display text-xl font-semibold">Architecture solide</h3><p class="mt-3 text-sm leading-6 text-slate-400">Des fondations testables, documentées et capables d’évoluer avec les contraintes métier.</p></article><article class="specular-card p-6"><div class="mb-4 text-2xl text-[#f59e0b]">◈</div><h3 class="font-display text-xl font-semibold">Exécution pragmatique</h3><p class="mt-3 text-sm leading-6 text-slate-400">Un équilibre entre qualité technique, vitesse de livraison et impact concret.</p></article></div></div></section>

    <section id="projets" class="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><div class="mb-8 flex items-end justify-between gap-4"><div><span class="code-label text-[#3b82f6]">02 // sélection</span><h2 class="mt-3 font-display text-3xl font-bold">Ce que j’ai construit</h2></div><span class="hidden font-mono text-xs text-slate-500 sm:block">projects --list --published</span></div><div class="grid gap-5 md:grid-cols-3">@forelse($projects as $project)<article class="specular-card p-6"><span class="code-label text-[#3b82f6]">{{ $project->category ?? 'project' }}</span><h3 class="mt-5 font-display text-xl font-semibold">{{ $project->title }}</h3><p class="mt-3 text-sm leading-6 text-slate-400">{{ $project->excerpt }}</p><div class="mt-6 flex flex-wrap gap-2 font-mono text-[11px] text-slate-500">@foreach($project->technologies ?? [] as $technology)<span class="rounded border border-[#1f2c47] px-2 py-1">{{ $technology }}</span>@endforeach</div></article>@empty<div class="specular-card p-6 text-sm text-slate-400 md:col-span-3">Les projets publiés seront affichés ici depuis le back-office.</div>@endforelse</div></section>

    <section id="competences" class="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><div class="specular-card grid gap-8 p-7 md:grid-cols-2 md:p-10"><div><span class="code-label text-[#3b82f6]">03 // toolkit</span><h2 class="mt-3 font-display text-3xl font-bold">Ma boîte à outils</h2><p class="mt-4 max-w-lg leading-7 text-slate-400">Backend, data, infrastructure et smart contracts : chaque outil est choisi pour servir un système fiable.</p></div><div class="grid grid-cols-2 gap-3 font-mono text-sm text-slate-300">@forelse($skills as $skill)<span class="rounded border border-[#1f2c47] bg-[#0b1120] p-3">{{ $skill->name }}</span>@empty<span class="col-span-2 text-sm text-slate-500">Les compétences seront gérées depuis l’administration.</span>@endforelse</div></div></section>

    <section id="experience" class="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><span class="code-label text-[#3b82f6]">04 // parcours</span><h2 class="mt-3 font-display text-3xl font-bold">Mon évolution</h2><div class="mt-8 border-l border-[#1f2c47] pl-6">@forelse($experiences as $experience)<div class="relative pb-8"><span class="absolute -left-[29px] top-1 h-2.5 w-2.5 rounded-full bg-[#3b82f6] shadow-[0_0_12px_#3b82f6]"></span><span class="font-mono text-xs text-[#3b82f6]">{{ $experience->is_current ? 'NOW' : $experience->start_date->format('Y') }}</span><h3 class="mt-2 font-display text-xl font-semibold">{{ $experience->role }}@if($experience->company) · {{ $experience->company }}@endif</h3><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-400">{{ $experience->description }}</p></div>@empty<div class="text-sm text-slate-500">Les expériences seront gérées depuis l’administration.</div>@endforelse</div></section>

    <section id="contact" class="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><div class="rounded-xl border border-[#f59e0b]/30 bg-[#f59e0b]/10 p-8"><div class="text-center"><span class="code-label text-[#f59e0b]">05 // contact_channel</span><h2 class="mt-3 font-display text-3xl font-bold">Construisons quelque chose de solide.</h2><p class="mx-auto mt-4 max-w-xl text-slate-300">Une idée, une architecture à challenger ou un projet à lancer ? Écrivez-moi.</p>@if(session('contact_success'))<p class="mt-4 text-sm text-emerald-400">{{ session('contact_success') }}</p>@endif</div><form method="POST" action="{{ route('contact.store') }}" class="mx-auto mt-8 grid max-w-3xl gap-4 sm:grid-cols-2">@csrf<input name="name" required maxlength="120" placeholder="Nom complet" class="rounded-lg border border-[#1f2c47] bg-[#0b1120] px-4 py-3 text-sm text-white outline-none focus:border-[#3b82f6]" value="{{ old('name') }}"><input name="email" required type="email" maxlength="255" placeholder="Email" class="rounded-lg border border-[#1f2c47] bg-[#0b1120] px-4 py-3 text-sm text-white outline-none focus:border-[#3b82f6]" value="{{ old('email') }}"><select name="project_type" class="rounded-lg border border-[#1f2c47] bg-[#0b1120] px-4 py-3 text-sm text-slate-300 outline-none focus:border-[#3b82f6]"><option value="">Type de projet</option><option value="backend">Backend / API</option><option value="blockchain">Blockchain</option><option value="recrutement">Recrutement</option></select><textarea name="message" required minlength="20" maxlength="5000" rows="4" placeholder="Votre message" class="sm:col-span-2 rounded-lg border border-[#1f2c47] bg-[#0b1120] px-4 py-3 text-sm text-white outline-none focus:border-[#3b82f6]">{{ old('message') }}</textarea><button class="sm:col-span-2 rounded-lg bg-[#f59e0b] px-5 py-3 text-sm font-bold text-[#0b1120] transition hover:bg-amber-300">Envoyer le message <span class="ml-2">↗</span></button></form></div></section>
</div>
@endsection
