@extends('admin.layout')
@section('title', $project->exists ? 'Modifier le projet' : 'Nouveau projet')
@section('section', 'Projets')
@section('content')
<div class="max-w-4xl"><h1 class="font-display text-3xl font-bold">{{ $project->exists ? 'Modifier le projet' : 'Nouveau projet' }}</h1>
<form class="mt-8 space-y-5 rounded-xl border border-[#1f2c47] bg-[#131c31] p-6" method="POST" enctype="multipart/form-data" action="{{ $project->exists ? route('admin.projects.update', $project) : route('admin.projects.store') }}">
@csrf @if($project->exists) @method('PUT') @endif
<div class="grid gap-5 sm:grid-cols-2"><label class="block text-sm">Titre<input name="title" required value="{{ old('title', $project->title) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">Slug<input name="slug" value="{{ old('slug', $project->slug) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">Catégorie<input name="category" value="{{ old('category', $project->category) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">Ordre<input name="sort_order" type="number" min="0" value="{{ old('sort_order', $project->sort_order ?? 0) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label></div>
<label class="block text-sm">Résumé<textarea name="excerpt" required rows="3" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5">{{ old('excerpt', $project->excerpt) }}</textarea></label>
<label class="block text-sm">Description<textarea name="description" rows="6" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5">{{ old('description', $project->description) }}</textarea></label>
<div class="grid gap-5 md:grid-cols-3"><label class="block text-sm">Problématique<textarea name="challenge" rows="5" placeholder="Quel besoin ou problème le projet résout-il ?" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5">{{ old('challenge', $project->challenge) }}</textarea></label><label class="block text-sm">Solution<textarea name="solution" rows="5" placeholder="Quelle approche et quelle architecture ?" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5">{{ old('solution', $project->solution) }}</textarea></label><label class="block text-sm">Résultats<textarea name="results" rows="5" placeholder="Quels résultats ou bénéfices concrets ?" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5">{{ old('results', $project->results) }}</textarea></label></div>
<label class="block text-sm">Technologies <span class="text-xs text-slate-500">séparées par des virgules</span><input name="technologies" value="{{ old('technologies', implode(', ', $project->technologies ?? [])) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label>
<label class="block text-sm">Image de couverture <span class="text-xs text-slate-500">JPG, PNG ou WEBP — 5 Mo maximum</span><input name="image" type="file" accept="image/jpeg,image/png,image/webp" class="mt-2 block w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5 text-sm"></label>
@if($project->image_path)<div><p class="mb-2 text-sm text-slate-400">Image actuelle</p><div class="w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] p-2 sm:w-72"><img src="{{ $project->image_url }}" alt="{{ $project->title }}" class="h-40 w-full rounded-md object-contain"><label class="mt-2 flex items-center gap-2 text-xs text-red-300"><input type="checkbox" name="remove_image" value="1"> Supprimer l’image actuelle</label></div><p class="mt-2 text-xs text-slate-500">Une nouvelle image remplacera automatiquement celle-ci.</p></div>@endif
<div class="rounded-lg border border-dashed border-[#334463] bg-[#0b1120] p-4"><label class="block text-sm font-semibold">Images supplémentaires <span class="font-normal text-xs text-slate-500">plusieurs fichiers possibles — 5 Mo chacun</span><input name="images[]" type="file" multiple accept="image/jpeg,image/png,image/webp" class="mt-3 block w-full text-sm text-slate-300 file:mr-4 file:rounded-lg file:border-0 file:bg-amber-400 file:px-4 file:py-2 file:font-bold file:text-[#0b1120]"></label>@if($project->gallery_paths)<div class="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">@foreach($project->gallery_paths as $galleryPath)<label class="group relative overflow-hidden rounded-lg border border-[#1f2c47]"><img src="{{ \Illuminate\Support\Facades\Storage::disk(config('filesystems.project_media_disk', 'public'))->url($galleryPath) }}" alt="Image du projet" class="h-24 w-full object-cover"><span class="absolute inset-x-0 bottom-0 flex items-center gap-2 bg-black/70 p-2 text-xs text-white"><input type="checkbox" name="remove_gallery[]" value="{{ $galleryPath }}"> Supprimer</span></label>@endforeach</div>@endif</div>
<div class="grid gap-5 sm:grid-cols-2"><label class="block text-sm">URL projet<input name="project_url" type="url" value="{{ old('project_url', $project->project_url) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">URL repository<input name="repository_url" type="url" value="{{ old('repository_url', $project->repository_url) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label></div>
<div class="flex flex-wrap gap-5 text-sm"><label><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $project->is_published))> Publié</label><label><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $project->is_featured))> À la une</label></div>
<div class="flex gap-3"><button class="rounded-lg bg-amber-400 px-5 py-3 font-bold text-[#0b1120]">Enregistrer</button><a href="{{ route('admin.projects.index') }}" class="rounded-lg border border-[#1f2c47] px-5 py-3">Annuler</a></div>
</form></div>
@endsection
