@extends('admin.layout')
@section('title', $project->exists ? 'Modifier le projet' : 'Nouveau projet')
@section('section', 'Projets')
@section('content')
<div class="max-w-4xl"><h1 class="font-display text-3xl font-bold">{{ $project->exists ? 'Modifier le projet' : 'Nouveau projet' }}</h1>
<form class="mt-8 space-y-5 rounded-xl border border-[#1f2c47] bg-[#131c31] p-6" method="POST" enctype="multipart/form-data" action="{{ $project->exists ? route('admin.projects.update', $project) : route('admin.projects.store') }}">
@csrf @if($project->exists) @method('PUT') @endif
<div class="grid gap-5 sm:grid-cols-2"><label class="block text-sm">Titre<input name="title" required value="{{ old('title', $project->title) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">Slug<input name="slug" value="{{ old('slug', $project->slug) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">Catégorie<input name="category" value="{{ old('category', $project->category) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">Ordre<input name="sort_order" type="number" min="0" value="{{ old('sort_order', $project->sort_order ?? 0) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label></div>
<label class="block text-sm">Résumé<textarea name="excerpt" required rows="3" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5">{{ old('excerpt', $project->excerpt) }}</textarea></label>
<label class="block text-sm">Description<textarea name="description" rows="6" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5">{{ old('description', $project->description) }}</textarea></label>
<label class="block text-sm">Technologies <span class="text-xs text-slate-500">séparées par des virgules</span><input name="technologies" value="{{ old('technologies', implode(', ', $project->technologies ?? [])) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label>
<label class="block text-sm">Image de couverture <span class="text-xs text-slate-500">JPG, PNG ou WEBP — 5 Mo maximum</span><input name="image" type="file" accept="image/jpeg,image/png,image/webp" class="mt-2 block w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5 text-sm"></label>
@if($project->image_path)<div><p class="mb-2 text-sm text-slate-400">Image actuelle</p><img src="{{ $project->image_url }}" alt="{{ $project->title }}" class="h-40 w-full rounded-lg object-cover sm:w-72"></div>@endif
<div class="grid gap-5 sm:grid-cols-2"><label class="block text-sm">URL projet<input name="project_url" type="url" value="{{ old('project_url', $project->project_url) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">URL repository<input name="repository_url" type="url" value="{{ old('repository_url', $project->repository_url) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label></div>
<div class="flex flex-wrap gap-5 text-sm"><label><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $project->is_published))> Publié</label><label><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $project->is_featured))> À la une</label></div>
<div class="flex gap-3"><button class="rounded-lg bg-amber-400 px-5 py-3 font-bold text-[#0b1120]">Enregistrer</button><a href="{{ route('admin.projects.index') }}" class="rounded-lg border border-[#1f2c47] px-5 py-3">Annuler</a></div>
</form></div>
@endsection
