@extends('admin.layout')
@section('title', $certification->exists ? 'Modifier la certification' : 'Nouvelle certification')
@section('section', 'Certifications')
@section('content')
<div class="max-w-3xl"><h1 class="font-display text-3xl font-bold">{{ $certification->exists ? 'Modifier la certification' : 'Nouvelle certification' }}</h1><form class="mt-8 space-y-5 rounded-xl border border-[#1f2c47] bg-[#131c31] p-6" method="POST" action="{{ $certification->exists ? route('admin.certifications.update', $certification) : route('admin.certifications.store') }}">@csrf @if($certification->exists) @method('PUT') @endif
<label class="block text-sm">Titre<input name="title" required value="{{ old('title', $certification->title) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label>
<div class="grid gap-5 sm:grid-cols-2"><label class="block text-sm">Organisme<input name="issuer" value="{{ old('issuer', $certification->issuer) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">Statut<input name="status" required value="{{ old('status', $certification->status ?? 'CERTIFIED') }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label></div>
<label class="block text-sm">Description<textarea name="description" rows="5" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5">{{ old('description', $certification->description) }}</textarea></label>
<div class="grid gap-5 sm:grid-cols-2"><label class="block text-sm">Identifiant<input name="credential_id" value="{{ old('credential_id', $certification->credential_id) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">Date<input name="issued_at" type="date" value="{{ old('issued_at', $certification->issued_at?->format('Y-m-d')) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">URL de vérification<input name="credential_url" type="url" value="{{ old('credential_url', $certification->credential_url) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">Ordre<input name="sort_order" type="number" min="0" value="{{ old('sort_order', $certification->sort_order ?? 0) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label></div>
<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_visible" value="1" @checked(old('is_visible', $certification->exists ? $certification->is_visible : true))> Visible sur le site</label><div class="flex gap-3"><button class="rounded-lg bg-amber-400 px-5 py-3 font-bold text-[#0b1120]">Enregistrer</button><a href="{{ route('admin.certifications.index') }}" class="rounded-lg border border-[#1f2c47] px-5 py-3">Annuler</a></div></form></div>
@endsection
