@extends('admin.layout')
@section('title', $certification->exists ? 'Modifier la certification' : 'Nouvelle certification')
@section('section', 'Certifications')
@section('content')
<div class="max-w-3xl"><h1 class="font-display text-3xl font-bold">{{ $certification->exists ? 'Modifier la certification' : 'Nouvelle certification' }}</h1><form class="mt-8 space-y-5 rounded-xl border border-[#1f2c47] bg-[#131c31] p-6" method="POST" enctype="multipart/form-data" action="{{ $certification->exists ? route('admin.certifications.update', $certification) : route('admin.certifications.store') }}">@csrf @if($certification->exists) @method('PUT') @endif
<label class="block text-sm">Titre<input name="title" required value="{{ old('title', $certification->title) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label>
<div class="grid gap-5 sm:grid-cols-2"><label class="block text-sm">Organisme<input name="issuer" value="{{ old('issuer', $certification->issuer) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">Statut<input name="status" required value="{{ old('status', $certification->status ?? 'CERTIFIED') }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label></div>
<label class="block text-sm">Description<textarea name="description" rows="5" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5">{{ old('description', $certification->description) }}</textarea></label>
<div class="rounded-lg border border-dashed border-[#334463] bg-[#0b1120] p-4"><label class="block text-sm font-semibold">Certificat à afficher <span class="font-normal text-slate-400">(PDF ou image, 10 Mo maximum)</span><input name="document" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" class="mt-3 block w-full text-sm text-slate-300 file:mr-4 file:rounded-lg file:border-0 file:bg-amber-400 file:px-4 file:py-2 file:font-bold file:text-[#0b1120]"></label>@if($certification->document_url)<div class="mt-4 flex items-center gap-4"><div class="h-20 w-28 overflow-hidden rounded-lg border border-[#1f2c47] bg-[#131c31]">@if($certification->document_type === 'application/pdf')<div class="flex h-full items-center justify-center font-mono text-xs text-amber-300">PDF</div>@else<img src="{{ $certification->document_url }}" alt="Aperçu du certificat" class="h-full w-full object-cover">@endif</div><a href="{{ $certification->document_url }}" target="_blank" rel="noopener" class="text-sm text-blue-400 hover:underline">Ouvrir le document actuel ↗</a></div>@endif</div>
<div class="grid gap-5 sm:grid-cols-2"><label class="block text-sm">Identifiant<input name="credential_id" value="{{ old('credential_id', $certification->credential_id) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">Date<input name="issued_at" type="date" value="{{ old('issued_at', $certification->issued_at?->format('Y-m-d')) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">URL de vérification<input name="credential_url" type="url" value="{{ old('credential_url', $certification->credential_url) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label><label class="block text-sm">Ordre<input name="sort_order" type="number" min="0" value="{{ old('sort_order', $certification->sort_order ?? 0) }}" class="mt-2 w-full rounded-lg border border-[#1f2c47] bg-[#0b1120] px-3 py-2.5"></label></div>
<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_visible" value="1" @checked(old('is_visible', $certification->exists ? $certification->is_visible : true))> Visible sur le site</label><div class="flex gap-3"><button class="rounded-lg bg-amber-400 px-5 py-3 font-bold text-[#0b1120]">Enregistrer</button><a href="{{ route('admin.certifications.index') }}" class="rounded-lg border border-[#1f2c47] px-5 py-3">Annuler</a></div></form></div>
@endsection
